name: Build macOS App

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 建议也更新 checkout 到 v4

      - name: Set up Python
        uses: actions/setup-python@v4  # 建议更新到 v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl pyinstaller

      - name: Build app
        run: |
          pyinstaller --onefile --windowed \
            --hidden-import=pandas \
            --hidden-import=pandas._libs.tslibs.timedeltas \
            --hidden-import=pandas._libs.tslibs.nattype \
            --hidden-import=pandas._libs.tslibs.timezones \
            --hidden-import=openpyxl \
            excel_reminder.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # 关键更新点
        with:
          name: excel-reminder-macos
          path: dist/excel_reminder
